[32mINFO    [0m root:test_ticket_module.py:34 接口用例数据：['2', '用户下单失败', 'http://127.0.0.1:8001', '/users/2/orders/', 'post', '{     "ticket_stall_id": 1,     "ticket_num": 2,     "viewers_id": [         "13579012345"     ] }', '"status": "error"', '', "{        'Content-Type': 'application/json',    'Accept': '*/*',    'Host': '127.0.0.1:8001',    'Connection': 'keep-alive' }", '']
[32mINFO    [0m root:request_util.py:72 请求头：{'Content-Type': 'application/json', 'Accept': '*/*', 'Host': '127.0.0.1:8001', 'Connection': 'keep-alive'}
[32mINFO    [0m root:request_util.py:11 请求原始数据：{     "ticket_stall_id": 1,     "ticket_num": 2,     "viewers_id": [         "13579012345"     ] }
[32mINFO    [0m root:request_util.py:81 Before sending: False
[32mINFO    [0m root:request_util.py:96 接口调用成功！
[32mINFO    [0m root:request_util.py:97 响应数据：{"message":"错误的参数个数","status":"error"}
[32mINFO    [0m root:request_util.py:48 无关联参数提取..
[32mINFO    [0m root:assert_util.py:12 【"status":"error"】关键字断言成功【{"message":"错误的参数个数","status":"error"}】